### ISSUE TITLE
bedrock example fails to build without --features bedrock

### ISSUE THREAD

**Issue by joshrotenberg** [joshrotenberg/claude-api#51]
## Summary

Running `cargo test --workspace` (or `cargo build --workspace --all-targets`) without explicit features fails to compile the `bedrock` example, because `crates/claude-api/examples/bedrock.rs` is not declared as an `[[example]]` entry with `required-features = ["bedrock"]` in `crates/claude-api/Cargo.toml`.

All other gated examples (basic, streaming, conversation, derived_tool, blocking, etc.) have proper `required-features` declarations; `bedrock.rs` was added in #40 but the `Cargo.toml` entry was missed.

## Repro

```sh
cargo build --workspace --all-targets
```

Output:

```
error[E0432]: unresolved import `claude_api::bedrock`
   --> crates/claude-api/examples/bedrock.rs:30:17
    |
 30 | use claude_api::bedrock::{BedrockCredentials, BedrockSigner};
    |                 ^^^^^^^ could not find `bedrock` in `claude_api`
    |
note: found an item that was configured out
   --> crates/claude-api/src/lib.rs:132:9
    |
130 | #[cfg(feature = "bedrock")]
    |       ------------------- the item is gated behind the `bedrock` feature

error[E0599]: no method named `bedrock` found for struct `ClientBuilder` in the current scope
  --> crates/claude-api/examples/bedrock.rs:47:10
   |
47 | |         .bedrock()
   | |         -^^^^^^^ method not found in `ClientBuilder`
```

With `--features bedrock` (or `--all-features`), the example compiles fine and all tests pass (52 tests across unit, integration, and doc tests).

## Fix

Add to `crates/claude-api/Cargo.toml`:

```toml
[[example]]
name = "bedrock"
required-features = ["async", "bedrock"]
```

## Impact

- Default `cargo test --workspace` and `cargo build --workspace --all-targets` invocations fail.
- CI runs that pass explicit feature flags may not catch this.
- Regression introduced in #40 (commit 74435b1).

## Environment

- Branch: main @ 74435b1
- rustc: workspace `rust-version = "1.90"`, edition 2024
- macOS Darwin 25.4.0

**Comment by joshrotenberg** [comment]
Duplicate of #48 (same root cause: the bedrock/managed_agents examples lacked required-features). Fixed by #58.
