### ISSUE TITLE
bedrock example missing required-features causes default build to fail

### ISSUE THREAD

**Issue by joshrotenberg** [joshrotenberg/claude-api#49]
## Summary

`cargo build --workspace --all-targets` (default features) fails to compile because `examples/bedrock.rs` references `claude_api::bedrock::*` and `ClientBuilder::bedrock()`, both of which are gated behind the `bedrock` cargo feature, but the example has no `required-features` entry in `crates/claude-api/Cargo.toml`.

Introduced in #40 (\`feat(bedrock): typed Messages namespace via .bedrock() flag\`), which added the example without the matching `[[example]]` entry. Every other feature-gated example in this crate already has `required-features` declared (see `conversation`, `typed_tools`, `derived_tool`, `blocking`, etc.), so this is just a missed entry.

## Reproduction

```
git checkout main
cargo build --workspace --all-targets
```

Errors:

```
error[E0432]: unresolved import \`claude_api::bedrock\`
  --> crates/claude-api/examples/bedrock.rs:30:17
   |
30 | use claude_api::bedrock::{BedrockCredentials, BedrockSigner};
   |                 ^^^^^^^ could not find \`bedrock\` in \`claude_api\`

error[E0599]: no method named \`bedrock\` found for struct \`ClientBuilder\` in the current scope
  --> crates/claude-api/examples/bedrock.rs:47:10
```

`cargo build --workspace --lib --bins --tests` and `cargo test --workspace --lib --bins --tests` (all 478+ tests) pass cleanly, and `cargo clippy --workspace --all-targets --all-features -- -D warnings` is also clean -- so the regression is scoped to building examples with default features only.

## Fix

Add a `[[example]]` entry to `crates/claude-api/Cargo.toml`:

```toml
[[example]]
name = "bedrock"
required-features = ["async", "bedrock"]
```

The example's own doc-comment already documents the correct invocation:

```
cargo run --example bedrock --no-default-features --features async,rustls,streaming,bedrock
```

so this just makes the Cargo metadata agree with the documented usage and prevents `--all-targets` builds from breaking.

## Environment

- Rust toolchain: stable (workspace `rust-version = "1.90"`, edition 2024)
- Branch: \`main\` at \`74435b1\`

**Comment by joshrotenberg** [comment]
Duplicate of #48 (same root cause: the bedrock/managed_agents examples lacked required-features). Fixed by #58.
