### ISSUE TITLE
bedrock example breaks `cargo build/test --workspace` (missing required-features)

### ISSUE THREAD

**Issue by joshrotenberg** [joshrotenberg/claude-api#47]
## Summary

`cargo build --workspace --all-targets` and `cargo test --workspace` both fail on a clean checkout (default features) because `crates/claude-api/examples/bedrock.rs` references the feature-gated `bedrock` module and the `.bedrock()` builder method, but the `[[example]]` entry for it in `crates/claude-api/Cargo.toml` does not declare `required-features`. Every other feature-gated example (`conversation`, `typed_tools`, `derived_tool`, `blocking`, etc.) declares its required features so cargo skips it when the features aren't enabled; `bedrock` is the only one missing this declaration.

## Repro

From a clean checkout on `main` (74435b1):

```
cargo build --example bedrock
```

```
error[E0432]: unresolved import `claude_api::bedrock`
  --> crates/claude-api/examples/bedrock.rs:30:17
   |
30 | use claude_api::bedrock::{BedrockCredentials, BedrockSigner};
   |                 ^^^^^^^ could not find `bedrock` in `claude_api`
   |
note: found an item that was configured out
  --> crates/claude-api/src/lib.rs:132:9

error[E0599]: no method named `bedrock` found for struct `ClientBuilder` in the current scope
  --> crates/claude-api/examples/bedrock.rs:47:10
   |
43 |       let client = Client::builder()
   |  __________________-
44 | |         .api_key("placeholder-bedrock-uses-sigv4")
45 | |         .signer(Arc::new(signer))
46 | |         .base_url(base_url)
47 | |         .bedrock()
   | |         -^^^^^^^ method not found in `ClientBuilder`
```

The same error blocks `cargo build --workspace --all-targets` and `cargo test --workspace`, since both implicitly build all examples.

## Impact

Anyone doing the standard workspace build/test commands hits a hard compile error. Workarounds are to scope the build (`--lib --tests`) or enable `--features bedrock` globally. Doctests, lib tests, and integration tests all pass cleanly otherwise (478 + 21 + ... = ~520 tests green).

## Suggested fix

Add to `crates/claude-api/Cargo.toml`, alongside the existing example declarations:

```toml
[[example]]
name = "bedrock"
required-features = ["async", "bedrock"]
```

This matches the doc comment at the top of `examples/bedrock.rs`, which already documents running it with `--features async,rustls,streaming,bedrock`.

## Notes

- Introduced in commit 74435b1 ("feat(bedrock): typed Messages namespace via .bedrock() flag (#40)").
- `examples/managed_agents.rs` and `examples/batches.rs` also live without `required-features` entries but currently compile because their modules aren't feature-gated under default features (`batches` is unconditional; `managed_agents` should arguably be gated, but that's a separate question).

**Comment by joshrotenberg** [comment]
Confirmed still reproducing on `main` at 74435b1 (mission `run-tests-anthropic-rs-bab4c1`).

Additional finding: when extending the repro to `cargo build -p claude-api --no-default-features`, two more examples hit the same root cause (missing `[[example]]` declaration with `required-features`):

- `batches` -- needs `async`
- `managed_agents` -- needs `async`, `managed-agents-preview`

Both reference modules that aren't in the type-only build. So the suggested fix probably wants to be a small batch:

```toml
[[example]]
name = "bedrock"
required-features = ["async", "bedrock"]

[[example]]
name = "batches"
required-features = ["async"]

[[example]]
name = "managed_agents"
required-features = ["async", "managed-agents-preview"]
```

`batches` and `managed_agents` happen to compile under default features (because `async` is on by default and they don't need a feature-gated module), so they only surface under `--no-default-features` or selective feature builds. Worth fixing at the same time -- otherwise `cargo build -p claude-api --no-default-features` (and presumably the type-only CI matrix row in CLAUDE.md) breaks the moment someone exercises it.

Test summary on a clean checkout: 478 lib + 21 live-replay + 5 record/replay + 7 cassette + 4 derive + 3+2+2 integration + 25 doctests all green once examples are excluded (`--lib --bins --tests`).

**Comment by joshrotenberg** [comment]
Duplicate of #48 (same root cause: the bedrock/managed_agents examples lacked required-features). Fixed by #58.
