### ISSUE TITLE
bedrock example fails to build with default features (missing required-features entry)

### ISSUE THREAD

**Issue by joshrotenberg** [joshrotenberg/claude-api#44]
## Summary

`cargo build --workspace --examples` (and `cargo test --workspace`) fails because `crates/claude-api/examples/bedrock.rs` has no `[[example]]` entry in `crates/claude-api/Cargo.toml`. Cargo auto-discovers the example and tries to compile it with default features, but the example imports `claude_api::bedrock` and calls `ClientBuilder::bedrock()`, both of which are gated behind the `bedrock` feature.

Introduced in #40 ("feat(bedrock): typed Messages namespace via .bedrock() flag"). The example file was added, but the matching `[[example]]` stanza with `required-features` was not.

## Reproduction

```sh
cargo build --workspace --examples
```

```
error[E0432]: unresolved import `claude_api::bedrock`
  --> crates/claude-api/examples/bedrock.rs:30:17
   |
30 | use claude_api::bedrock::{BedrockCredentials, BedrockSigner};
   |                 ^^^^^^^ could not find `bedrock` in `claude_api`

error[E0599]: no method named `bedrock` found for struct `ClientBuilder` in the current scope
  --> crates/claude-api/examples/bedrock.rs:47:10
   |
43 |       let client = Client::builder()
   |  __________________-
44 | |         .api_key("placeholder-bedrock-uses-sigv4")
45 | |         .signer(Arc::new(signer))
46 | |         .base_url(base_url)
47 | |         .bedrock()
   | |         -^^^^^^^ method not found in `ClientBuilder`

error: could not compile `claude-api` (example "bedrock") due to 2 previous errors
```

Building with the feature works fine:

```sh
cargo build --example bedrock --features bedrock   # ok
```

## Impact

- `cargo build --workspace --examples` fails.
- `cargo test --workspace` fails (it compiles examples as part of the test build).
- CI on the workspace will trip on this unless examples are explicitly excluded.

## Suggested fix

Add an `[[example]]` entry to `crates/claude-api/Cargo.toml`, matching the pattern used for the other gated examples:

```toml
[[example]]
name = "bedrock"
required-features = ["async", "bedrock"]
```

A similar entry for any planned `vertex` example would also be a good idea once one lands.

## Notes / additional context

- All 523 unit/integration tests pass (`cargo test --workspace --lib --bins --tests`).
- All doctests pass.
- `examples/managed_agents.rs` also lacks an `[[example]]` entry, but it currently compiles under `--workspace` only because `claude-api-test`'s dev-dependencies enable the `managed-agents-preview` feature, which unifies feature flags across the workspace. Building it in isolation (`cargo build -p claude-api --examples`) reproduces a similar failure. Consider adding a `required-features = ["async", "managed-agents-preview"]` entry for it too, so it doesn't depend on workspace feature unification.

Environment: `darwin 25.4.0`, Rust toolchain per `rust-version = "1.90"` from the workspace `Cargo.toml`.

**Comment by joshrotenberg** [comment]
Duplicate of #48 (same root cause: the bedrock/managed_agents examples lacked required-features). Fixed by #58.
